### PR TITLE
updating build.yml & pom.xml

### PR DESCRIPTION
**Pull request by ishu-thakur**
Hi @mfvanek
I have updated pom.xml:
java version from 12 to 17.
maven-enforcer-plugin config was already upto version 3.1.0.
Updated build.yml:
java version and JDK from 12 to 17 .

### CODE REVIEW

**Comment by mfvanek** [comment]
@ishu-thakur 

1. Configuration of enforcer plugin must be updated
2. **Error**:  Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd (pmd) on project BookcrossingServer: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.13.0:pmd failed: org.apache.maven.reporting.MavenReportException: Unsupported targetJdk value '17'. -> [Help 1]

**Comment by mfvanek** [comment]
@ishu-thakur 
Local tests run should be fixed after https://github.com/EnKarin/BookCrossingServer/pull/70

I've moved sonar checks to a separate profile

**Review by mfvanek — CHANGES_REQUESTED** [review]
Conflicts must be resolved

**Review by EnKarin — COMMENTED** [review]
It is necessary to reassemble and correct the comments

**Pull request closed without merging**
